### ISSUE TITLE
PATH not being set correctly.

### ISSUE THREAD

**Issue by lewis-john-lloyd** [rtmclay/Lmod_test_suite#2]
For some reason when I try to use this on a SUSE 13 Service Patch 3 node from the tcsh shell, the PATH variable for the t1.script does not contain /bin. This leads to t1.log containing a large number of error messages as you would expect. I am not sure what it is about the particular system configuration that is causing the particular issue.  When I tried to use the test suite on a Linux Mint distribution, the results were much more positive. However, there were still some oddities such as terminal width impact acceptance of a result.

This is what caused the "avail" test to fail.
--- _err.left   2017-01-18 21:52:01.397445390 -0500
+++ _err.right  2017-01-18 21:52:01.405445553 -0500
@@ -2,5 +2,4 @@
 ProjectDIR/rt/avail/mf/Core
    A/1.0    B/2.0
 Use "module spider" to find all possible modules.
-Use "module keyword key1 key2 ..." to search for all possible modules matching
-any of the "keys".
+Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

Anyways, I am not sure what is causing the SUSE one to fail in the path aspect. Any ideas?

**Comment by rtmclay** [comment]
Thanks for the bug report! I have fixed the avail test so that it do the right thing independent of the terminal width.  I have release version 1.1 to fix the avail problem.

The problem with SUSE is likely to be in the way that Hermes tries to keep a minimum PATH.  I have fixed hermes so that it keeps /bin in the PATH.  Please try release 2.3 from hermes to see if it fixes the problem on SUSE for you

**Comment by lewis-john-lloyd** [comment]
Using lua-5.1.4.8 and Hermes-2.3, I am not seeing /bin in the PATH provided by Lmod_test_suite-1.1.

**Comment by lewis-john-lloyd** [comment]
Alright, instead of complaining, here is the issue:

In the local function cleanPath in CleanEnv.lua in Hermes 2.3, the block of code starting at line 56 adds /usr/bin and /bin to pathT as a "keep" only if they are not already in pathT. The directory '/usr/bin' is being kept because of the block of code at starting at line 77.  I think that you want the "==" on line 60 to be a "~=", which fixes this issue for me.

**Comment by rtmclay** [comment]
Thanks.  Obviously what I had didn't work.  I had to tweak your fix slightly.  I have pushed a new version of Hermes (2.4).  If you get the chance, please test out Hermes 2.4.  Thanks for the feedback!
